apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-ozijvikf
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-ozijvikf:7d16191b1b68ba737a8d450917342fefda790534@sha256:3d59b45dbc9e3e0c535ea019917a7b5e2ea920395d01fafa564e90be80501925
          name: container-image
